### PR TITLE
==file add

### PR DESCRIPTION
**Pull request by 1hyyang**
<class>
AttachVO.java

==code edit
<class>
ClassVO.java
<content>
	private int location_no; 삭제
	private String exercise_no; 추가
	private String nickname; 추가
 	private String exercise_name; 추가

==code edit
<class>
	ExerciseVO.java
<content>
	private int exercise_no; -> private String exercise_no;

==code edit
<class>
	LocationVO.java
<content>
	private int location_no; -> private String location_no;
	private String class_no; 추가

==code edit
<class>
	ReviewVO.java
<content>
	private int review_no;
	private int member_no;
	private int class_no;
	->
 	private String review_no;
	private String member_no;
	private String class_no;

==code edit
<class>
	ScrapVO.java
<content>
	private int scrap_no;
	private int class_no;
	private int member_no;
	->
	private String scrap_no;
	private String class_no;
	private String member_no;

==code edit
<build?>
	pom.xml
<content>
	thumbnailator 추가
	aspectjweaver 추가

==code edit
<package>
	com.healpio.test
<class>
	BoardTest.java
<content>
	log.info(board.getLocation_no()); 삭제

### CODE REVIEW

**Review by geonwoo05 — APPROVED** [review]
확인했습니다.

**Review by yoojin0219 — APPROVED** [review]
확인했습니다.

**Review by YangSungJoon — APPROVED** [review]
확인했습니다. 양이 장난 아니에요 ㅠ

**Review by NovaCodingI — APPROVED** [review]
확인 완료 했습니다
고생하셨습니다

**Pull request merged**
